name: Question-2

on:
  push:
    branches: [ "main" ]
    paths: [ "Q2/**" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: change directory
        run: cd Q2/
      - name: Build the Docker image
        run: docker build -t my-image Q2/Dockerfile

      - name: Run the code
        run: docker run my-image